name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  packages: write # to be able to publish a Docker image


jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19
          branches: |
            [
              "main"
            ]

  docker:
    name: Build and Push Docker Image
    needs: release
    if: needs.release.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: Detect changed directories
        id: changes
        uses: tj-actions/changed-files@v46
        with:
          files_yaml: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

      - name: Log in to the Container registry
        if: steps.changes.outputs.backend_any_changed == 'true' || steps.changes.outputs.frontend_any_changed == 'true'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Repository Owner
        if: steps.changes.outputs.backend_any_changed == 'true' || steps.changes.outputs.frontend_any_changed == 'true'
        run: echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

      - name: Build and push backend Docker image
        if: steps.changes.outputs.backend_any_changed == 'true'
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          build-args: VERSION=${{ needs.release.outputs.new_release_version }}
          tags: ghcr.io/${{ env.OWNER }}/lime-tracker-backend:latest,ghcr.io/${{ env.OWNER }}/lime-tracker-backend:${{ needs.release.outputs.new_release_version }}

      - name: Build and push frontend Docker image
        if: steps.changes.outputs.frontend_any_changed == 'true'
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          build-args: VERSION=${{ needs.release.outputs.new_release_version }}
          tags: ghcr.io/${{ env.OWNER }}/lime-tracker-frontend:latest,ghcr.io/${{ env.OWNER }}/lime-tracker-frontend:${{ needs.release.outputs.new_release_version }}

