name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  packages: write # to be able to publish a Docker image


jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 19
          branches: |
            [
              "main"
            ]

  docker:
    name: Build and Push Docker Image
    needs: release
    if: needs.release.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Lowercase Repository Name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ env.REPO }}/mac-checker:latest,ghcr.io/${{ env.REPO }}/mac-checker:${{ needs.release.outputs.new_release_version }}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO }}/mac-checker:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO }}/mac-checker:buildcache,mode=max

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ env.REPO }}/lime-tracker:latest,ghcr.io/${{ env.REPO }}/lime-tracker:${{ needs.release.outputs.new_release_version }}
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO }}/lime-tracker:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO }}/lime-tracker:buildcache,mode=max

